name: Windows x86_64 only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bison ccache cmake diffutils git make ruby
          sudo apt install -y ninja-build python3-pip
          pip3 install meson
          sudo apt install -y gcc g++ mingw-w64

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir="$(pwd)/ccache"
          ccache --set-config=compiler_check=content
          ccache --set-config=max_size=1280MiB

      - name: Configure
        run: meson setup --prefix "$(pwd)/build/artifact" --cross-file windows/meson-gcc-x86_64.txt --buildtype release -Dstrip=true -Db_lto=true build

      - name: Build
        run: CLICOLOR_FORCE=1 ninja -C build -v

      - name: Prepare artifact
        run: meson install -C build --no-rebuild --tags mkxp-z

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: mkxp-z-windows-x86_64
          path: build/artifact
